// Catálogo de estaciones hidrométricas (claves = nombre de Prefectura normalizado)
// seg: tramo del mapa que colorea la estación. key: estación de referencia para el índice.
// Coordenadas aproximadas (puerto / escala hidrométrica).
export const STATIONS = {
  // Río Iguazú
  'CAXIA (BRASIL)': { name: 'Salto Caxias (BR)', lat: -25.54, lon: -53.49, seg: 'iguazu', kind: 'embalse', country: 'BR' },
  'REPRESA CAPANEMA (BRASIL)': { name: 'Capanema (BR)', lat: -25.57, lon: -53.80, seg: 'iguazu', kind: 'embalse', country: 'BR' },
  'ANDRESITO': { name: 'Andresito', lat: -25.58, lon: -54.03, seg: 'iguazu' },
  'IGUAZU': { name: 'Puerto Iguazú', lat: -25.60, lon: -54.58, seg: 'iguazu' },
  // Alto Paraná
  'GUAYRA (BRASIL)': { name: 'Guaíra (BR)', lat: -24.07, lon: -54.26, seg: 'parana-alto', kind: 'embalse', country: 'BR' },
  'REPRESA ITAIPU (BRASIL)': { name: 'Itaipú (BR/PY)', lat: -25.41, lon: -54.59, seg: 'parana-alto', kind: 'embalse', country: 'BR' },
  'LIBERTAD': { name: 'Libertad', lat: -25.92, lon: -54.62, seg: 'parana-alto' },
  'ELDORADO': { name: 'Eldorado', lat: -26.40, lon: -54.69, seg: 'parana-alto' },
  'LIBERTADOR': { name: 'Libertador Gral. San Martín', lat: -26.80, lon: -55.05, seg: 'parana-alto' },
  'PUERTO MANI': { name: 'Puerto Maní', lat: -27.20, lon: -55.45, seg: 'parana-alto' },
  'SANTA ANA': { name: 'Santa Ana', lat: -27.37, lon: -55.58, seg: 'parana-alto' },
  'POSADAS': { name: 'Posadas', lat: -27.36, lon: -55.89, seg: 'parana-alto', key: true },
  'ITUZAINGO': { name: 'Ituzaingó', lat: -27.59, lon: -56.68, seg: 'parana-alto' },
  'ITA IBATE': { name: 'Itá Ibaté', lat: -27.43, lon: -57.34, seg: 'parana-alto' },
  'ITATI': { name: 'Itatí', lat: -27.27, lon: -58.24, seg: 'parana-alto' },
  'PASO DE LA PATRIA': { name: 'Paso de la Patria', lat: -27.32, lon: -58.57, seg: 'parana-alto' },
  // Paraná medio e inferior
  'CORRIENTES': { name: 'Corrientes', lat: -27.47, lon: -58.84, seg: 'parana-bajo', key: true },
  'BARRANQUERAS': { name: 'Barranqueras', lat: -27.48, lon: -58.94, seg: 'parana-bajo' },
  'EMPEDRADO': { name: 'Empedrado', lat: -27.95, lon: -58.81, seg: 'parana-bajo' },
  'BELLA VISTA': { name: 'Bella Vista', lat: -28.51, lon: -59.05, seg: 'parana-bajo' },
  'GOYA': { name: 'Goya', lat: -29.14, lon: -59.26, seg: 'parana-bajo', key: true },
  'RECONQUISTA': { name: 'Reconquista', lat: -29.23, lon: -59.60, seg: 'parana-bajo', key: true },
  'ESQUINA': { name: 'Esquina', lat: -30.01, lon: -59.53, seg: 'parana-bajo' },
  'SAN JAVIER (SANTA FE)': { name: 'San Javier (SF)', lat: -30.58, lon: -59.93, seg: 'parana-bajo' },
  'LA PAZ': { name: 'La Paz', lat: -30.74, lon: -59.65, seg: 'parana-bajo', key: true },
  'SANTA ELENA': { name: 'Santa Elena', lat: -30.95, lon: -59.80, seg: 'parana-bajo' },
  'HERNANDARIAS': { name: 'Hernandarias', lat: -31.23, lon: -59.99, seg: 'parana-bajo' },
  'PARANA': { name: 'Paraná', lat: -31.72, lon: -60.52, seg: 'parana-bajo', key: true },
  'SANTA FE': { name: 'Santa Fe', lat: -31.65, lon: -60.70, seg: 'parana-bajo', key: true },
  'DIAMANTE': { name: 'Diamante', lat: -32.07, lon: -60.64, seg: 'parana-bajo' },
  'VICTORIA': { name: 'Victoria', lat: -32.62, lon: -60.15, seg: 'parana-bajo' },
  'SAN LORENZO': { name: 'San Lorenzo', lat: -32.75, lon: -60.73, seg: 'parana-bajo' },
  'ROSARIO': { name: 'Rosario', lat: -32.95, lon: -60.63, seg: 'parana-bajo', key: true },
  'VILLA CONSTITUCION': { name: 'Villa Constitución', lat: -33.23, lon: -60.33, seg: 'parana-delta' },
  'SAN NICOLAS': { name: 'San Nicolás', lat: -33.33, lon: -60.21, seg: 'parana-delta', key: true },
  'RAMALLO': { name: 'Ramallo', lat: -33.48, lon: -60.00, seg: 'parana-delta' },
  'SAN PEDRO': { name: 'San Pedro', lat: -33.68, lon: -59.66, seg: 'parana-delta' },
  'BARADERO': { name: 'Baradero', lat: -33.81, lon: -59.50, seg: 'parana-delta' },
  'ZARATE': { name: 'Zárate', lat: -34.10, lon: -59.03, seg: 'parana-delta' },
  'CAMPANA': { name: 'Campana', lat: -34.17, lon: -58.95, seg: 'parana-delta' },
  'ESCOBAR': { name: 'Escobar', lat: -34.33, lon: -58.75, seg: 'parana-delta' },
  'CANAL NUEVO': { name: 'Canal Nuevo', lat: -34.27, lon: -58.60, seg: 'parana-delta' },
  'PUERTO RUIZ': { name: 'Puerto Ruiz', lat: -33.22, lon: -59.38, seg: 'parana-delta' },
  'IBICUY': { name: 'Ibicuy', lat: -33.74, lon: -59.16, seg: 'parana-delta' },
  'GUAZUCITO': { name: 'Guazucito', lat: -34.00, lon: -58.66, seg: 'parana-delta' },
  'MARTIN GARCIA': { name: 'Martín García', lat: -34.18, lon: -58.25, seg: 'parana-delta' },
  'TIGRE': { name: 'Tigre', lat: -34.42, lon: -58.58, seg: 'parana-delta' },
  'DIQUE LUJAN': { name: 'Dique Luján', lat: -34.36, lon: -58.68, seg: 'parana-delta' },
  'CHANA MINI': { name: 'Chaná Miní', lat: -34.15, lon: -58.62, seg: 'parana-delta' },
  'SAN FERNANDO': { name: 'San Fernando', lat: -34.44, lon: -58.55, seg: 'parana-delta' },
  'SAN ISIDRO': { name: 'San Isidro', lat: -34.47, lon: -58.50, seg: 'parana-delta' },
  'OLIVOS': { name: 'Olivos', lat: -34.51, lon: -58.48, seg: 'parana-delta' },
  // Río Paraguay
  'PILCOMAYO': { name: 'Puerto Pilcomayo', lat: -25.37, lon: -57.65, seg: 'paraguay' },
  'BOUVIER': { name: 'Puerto Bouvier', lat: -25.85, lon: -57.93, seg: 'paraguay' },
  'FORMOSA': { name: 'Formosa', lat: -26.18, lon: -58.17, seg: 'paraguay', key: true },
  'BERMEJO': { name: 'Puerto Bermejo', lat: -26.93, lon: -58.51, seg: 'paraguay' },
  'LAS PALMAS': { name: 'Las Palmas', lat: -27.07, lon: -58.68, seg: 'paraguay' },
  'ISLA DEL CERRITO': { name: 'Isla del Cerrito', lat: -27.29, lon: -58.61, seg: 'paraguay' },
  // Río Uruguay
  'EL SOBERBIO': { name: 'El Soberbio', lat: -27.30, lon: -54.20, seg: 'uruguay' },
  'ALBA POSSE': { name: 'Alba Posse', lat: -27.57, lon: -54.68, seg: 'uruguay' },
  'PANAMBI': { name: 'Panambí', lat: -27.72, lon: -54.92, seg: 'uruguay' },
  'SAN JAVIER': { name: 'San Javier (Mnes.)', lat: -27.87, lon: -55.13, seg: 'uruguay' },
  'PUERTO CONCEPCION': { name: 'Concepción de la Sierra', lat: -27.98, lon: -55.52, seg: 'uruguay' },
  'GARRUCHOS': { name: 'Garruchos', lat: -28.17, lon: -55.65, seg: 'uruguay' },
  'SANTO TOME': { name: 'Santo Tomé', lat: -28.55, lon: -56.04, seg: 'uruguay' },
  'ALVEAR': { name: 'Alvear', lat: -29.10, lon: -56.55, seg: 'uruguay' },
  'LA CRUZ': { name: 'La Cruz', lat: -29.17, lon: -56.64, seg: 'uruguay' },
  'YAPEYU': { name: 'Yapeyú', lat: -29.47, lon: -56.82, seg: 'uruguay' },
  'PASO DE LOS LIBRES': { name: 'Paso de los Libres', lat: -29.71, lon: -57.08, seg: 'uruguay' },
  'BOMPLAND': { name: 'Bonpland', lat: -29.82, lon: -57.43, seg: 'uruguay' },
  'MONTE CASEROS': { name: 'Monte Caseros', lat: -30.25, lon: -57.64, seg: 'uruguay' },
  'MOCORETA': { name: 'Mocoretá', lat: -30.62, lon: -57.96, seg: 'uruguay' },
  'FEDERACION': { name: 'Federación', lat: -30.98, lon: -57.92, seg: 'uruguay' },
  'FEDERACION EMBALSE': { name: 'Embalse Salto Grande', lat: -31.00, lon: -57.90, seg: 'uruguay', kind: 'embalse', map: false },
  'SALTO GRANDE ARRIBA': { name: 'Salto Grande (arriba)', lat: -31.27, lon: -57.94, seg: 'uruguay', kind: 'embalse', map: false },
  'SALTO GRANDE ABAJO': { name: 'Salto Grande (abajo)', lat: -31.29, lon: -57.95, seg: 'uruguay', map: false },
  'CONCORDIA': { name: 'Concordia', lat: -31.39, lon: -58.02, seg: 'uruguay' },
  'COLON': { name: 'Colón', lat: -32.22, lon: -58.14, seg: 'uruguay' },
  'CONCEPCION DEL URUGUAY': { name: 'Concepción del Uruguay', lat: -32.48, lon: -58.23, seg: 'uruguay' },
  'BOCA GUALEGUAYCHU': { name: 'Boca Gualeguaychú', lat: -33.07, lon: -58.42, seg: 'uruguay' },
};

// Nodos del modelo GloFAS (Open-Meteo Flood API). lat/lon = punto aproximado sobre el cauce;
// glat/glon: celda GloFAS "enganchada" (mayor caudal en ±0.10°); build-climatology.mjs la recalcula.
export const GLOFAS_NODES = [
  { id: 'jupia', name: 'Paraná en Jupiá (BR)', lat: -20.78, lon: -51.63, glat: -20.725, glon: -51.675, seg: 'parana-alto', upstream: true },
  { id: 'guaira', name: 'Paraná en Guaíra (BR)', lat: -24.07, lon: -54.26, glat: -24.175, glon: -54.375, seg: 'parana-alto', upstream: true },
  { id: 'itaipu', name: 'Paraná aguas abajo de Itaipú', lat: -25.45, lon: -54.60, glat: -25.325, glon: -54.575, seg: 'parana-alto', upstream: true, key: true },
  { id: 'iguazu', name: 'Iguazú en Cataratas', lat: -25.62, lon: -54.30, glat: -25.625, glon: -54.425, seg: 'iguazu', upstream: true, key: true },
  { id: 'corumba', name: 'Paraguay en Corumbá (BR)', lat: -19.00, lon: -57.60, glat: -19.025, glon: -57.625, seg: 'paraguay', upstream: true },
  { id: 'asuncion', name: 'Paraguay en Asunción', lat: -25.27, lon: -57.66, glat: -25.275, glon: -57.725, seg: 'paraguay', upstream: true, key: true },
  { id: 'bermejo', name: 'Bermejo en El Colorado', lat: -26.33, lon: -59.37, glat: -26.225, glon: -59.475, seg: 'bermejo' },
  { id: 'posadas', name: 'Paraná en Posadas', lat: -27.37, lon: -55.88, glat: -27.325, glon: -55.925, seg: 'parana-alto' },
  { id: 'corrientes', name: 'Paraná en Corrientes', lat: -27.47, lon: -58.85, glat: -27.575, glon: -58.875, seg: 'parana-bajo', key: true },
  { id: 'goya', name: 'Paraná en Goya', lat: -29.10, lon: -59.30, glat: -29.025, glon: -59.275, seg: 'parana-bajo' },
  { id: 'santafe', name: 'Paraná en Santa Fe / Paraná', lat: -31.70, lon: -60.52, glat: -31.725, glon: -60.625, seg: 'parana-bajo', key: true },
  { id: 'rosario', name: 'Paraná en Rosario', lat: -32.95, lon: -60.62, glat: -32.975, glon: -60.675, seg: 'parana-bajo' },
  { id: 'santotome', name: 'Uruguay en Santo Tomé', lat: -28.55, lon: -56.03, glat: -28.675, glon: -56.125, seg: 'uruguay' },
  { id: 'saltogrande', name: 'Uruguay en Salto Grande', lat: -31.27, lon: -57.94, glat: -31.375, glon: -58.025, seg: 'uruguay' },
];

// Zonas de precipitación pronosticada (Open-Meteo Forecast API)
export const RAIN_ZONES = [
  { id: 'alto-parana-br', name: 'Alto Paraná (Brasil)', lat: -22.5, lon: -52.0, upstream: true },
  { id: 'parana-itaipu', name: 'Paraná – Itaipú', lat: -24.5, lon: -53.8, upstream: true },
  { id: 'iguazu', name: 'Cuenca del Iguazú', lat: -25.8, lon: -52.0, upstream: true },
  { id: 'pantanal', name: 'Pantanal (Paraguay superior)', lat: -19.0, lon: -57.0, upstream: true },
  { id: 'paraguay-medio', name: 'Paraguay medio', lat: -23.8, lon: -57.5, upstream: true },
  { id: 'misiones', name: 'Misiones', lat: -27.0, lon: -55.0, upstream: true },
  { id: 'uruguay-alto', name: 'Alto Uruguay', lat: -27.6, lon: -52.5 },
  { id: 'litoral', name: 'Corrientes / Chaco', lat: -28.8, lon: -58.8 },
  { id: 'santa-fe', name: 'Santa Fe / Entre Ríos', lat: -31.6, lon: -60.2 },
];

export const normalizeName = (s) =>
  String(s || '').normalize('NFD').replace(/[̀-ͯ]/g, '').toUpperCase().replace(/\s+/g, ' ').trim();
